compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU #NO
downcast_bf16: 'yes'
gpu_ids: 0,1 #"0"
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 2 #2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 0